trigger:
- master

pool: Azure Pipelines

steps:
- task: GoogleCloudSdkInstaller@0
  displayName: 'Google Cloud SDK Install'
  inputs:
    version: '306.0.0'

- task: DownloadSecureFile@1
  displayName: 'Download service-account.json'
  name: mySecureFile
  inputs:
    secureFile: '$(service_account_filename)'
    retryCount: '3'

- task: CmdLine@2
  displayName: 'GCloud Login'
  inputs:
    script: |
      gcloud components update kubectl -q
      gcloud auth activate-service-account --key-file $(mySecureFile.secureFilePath)
      gcloud config set project $(project_id)
      gcloud config set compute/zone $(compute_zone)
      gcloud container clusters get-credentials $(cluster_name)
    workingDirectory: '$(Build.SourcesDirectory)'

# - task: ArchiveFiles@2
#   inputs:
#     rootFolderOrFile: '$(Build.SourcesDirectory)'
#     includeRootFolder: false
#     archiveType: 'zip'
#     archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildNumber).zip'
#     replaceExistingArchive: true
    
# - task: PublishBuildArtifacts@1
#   displayName: 'Publish Artifact: drop'
#   inputs:
#     PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildNumber).zip'