trigger:
- master

pool: Azure Pipelines

steps:
- task: GoogleCloudSdkInstaller@0
  displayName: 'Google Cloud SDK Install'
  inputs:
    version: '306.0.0'

- task: DownloadSecureFile@1
  displayName: 'Download service-account.json'
  name: mySecureFile
  inputs:
    secureFile: '$(service_account_filename)'
    retryCount: '3'

- task: CmdLine@2
  displayName: 'GCloud Login'
  inputs:
    script: |
      export CLOUDSDK_CORE_DISABLE_PROMPTS=1
      gcloud components update kubectl
      gcloud auth activate-service-account --key-file $(mySecureFile.secureFilePath)
      gcloud config set project $(project_id)
      gcloud config set compute/zone $(compute_zone)
      gcloud container clusters get-credentials $(cluster_name)
    workingDirectory: '$(Build.SourcesDirectory)'

- task: CmdLine@2
  displayName: 'Run TestCases'
  inputs:
    script: |
      echo "$(DOCKER_PASSWORD)" | docker login -u "$(DOCKER_USERNAME)" --password-stdin
      docker build -t $(DOCKER_USERNAME)/react-test -f ./client/Dockerfile.dev ./client
      docker run -e CI=true $(DOCKER_USERNAME)/react-test npm test
    workingDirectory: '$(Build.SourcesDirectory)'

- task: CmdLine@2
  displayName: 'Kubernetes Deployment'
  inputs:
    script: |
      export SHA=$(git rev-parse HEAD)
      chmod +x deploy.sh
      ./deploy.sh
    workingDirectory: '$(Build.SourcesDirectory)'